name: riverpod_go_money_book
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  flutter_riverpod: ^2.3.5
  riverpod_annotation:
  go_router: ^6.5.7
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  riverpod_generator:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
